### ISSUE TITLE
XCode 빌드 오류 질문

### ISSUE THREAD

**Issue by minsoo5403** [heyask/MyUnityPlugin-ios#1]
환경 : Catalina 10.15.6 / XCode 12

증상 : 
MyUnityPlugin - 빌드 성공
MyUnityPluginBridge - 빌드 실패

MyUnityPluginUnityProtocol.m 파일에서  UnitySendMessage 메소드에 'Implicit declaration of function 'UnitySendMessage' is invalid in C99' 오류 발생

의견 : 
MyUnityPlugin 을 빌드한 이후 MyUnityPluginBridge 에 .framework를 추가하고 MyUnityPluginBridge 프로젝트 빌드를 진행하는 순서가 아닌가요 ?

**Comment by heyask** [comment]
MyUnityPluginBridge 프로젝트를 xcode 상에서 빌드하면 해당 에러가 발생하는게 맞습니다. 
유니티 관련 헤더파일들이 없기 때문인데요. (`UnityInterface.h`, `UnityForwardDecls.h` 등)
MyUnityPluginBridge 프로젝트는 유니티 프로젝트에 넣은 후 유니티상에서 빌드하면 에러가 발생하지 않습니다.

**Comment by minsoo5403** [comment]
아.. 제가 이해가 부족했었네요. 답변 감사합니다 ㅎㅎ !
